#!/bin/bash
#/**
#@file    TimeFreezeDisable
#@brief   Guión de rutinas que se ejecutarán en los windows de EVLT.
#@param   $1 número de disco
#@param   $2 número de particion
#@exception OG_ERR_FORMAT   1 formato incorrecto.
#@exception OG_ERR_NOTFOUND  2 fichero de imagen o partición no detectados.
#@exception OG_ERR_PARTITION 3	# Error en partición de disco.
#@exception OG_ERR_LOCKED    4 partición bloqueada por otra operación.
#@version 1.0.1 - primera version
#@author  Antonio J. Doblas Viso.
#@date    2017-02-23
#**/





PROG="$(basename $0)"
if [ $# -lt 2 ]; then
    ogRaiseError session $OG_ERR_FORMAT "$MSG_FORMAT: $PROG  ndisco nparticion"
    exit $?
fi


# Asignación de variables (repositorio y protocolo se convierten a mayúsculas).
################ Bloque de variables ####################
DISK=$1
PART=$2
POSTCONF=postconf.cmd
### Bloque de variables EVLT
source $OGETC/os.cfg $DISK $PART



## Creamos los ficheros. 
#ogSetWinMSWinActivate $1 $2
#ogSetWinMSOfficeActivate $1 $2


OSVERSION=$(ogGetOsVersion $1 $2)
case "$OSVERSION" in
    *Windows*)
		## Indicación del proceso (variable $POSTCONF), usuario que lo ejecutará ($ADMIN) y configuración del windows para que arranque con autologin tras la postconfiguración (1 "$USER" "$PASSUSER")
		echo "ogInstallMiniSetup $DISK $PART $POSTCONF $ADMIN $PASSADMIN 1 \"$USER\" \"$PASSUSER\" "
		ogInstallMiniSetup $DISK $PART $POSTCONF $ADMIN $PASSADMIN 1 "$USER" "$PASSUSER"
		ogAddCmd $DISK $PART $POSTCONF '@echo off'		
		ogAddCmd $DISK $PART $POSTCONF '"c:\Program Files\Toolwiz Time Freeze 2017\ToolwizTimeFreeze.exe" /unfreeze  /usepass=imagen17EVLT'
		### reiniciamos el equipo
		ogAddCmd $DISK $PART $POSTCONF "shutdown -r"

	;;
esac

